---
#________________________ Install Docker ________________________#
- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Change ownership of docker.sock
  file:
    path: /var/run/docker.sock
    owner: root
    group: docker
    state: touch

- name: change docker.sock file permissions
  file:
    path: /var/run/docker.sock
    mode: "0666"

- name: restart jenkins & docker
  service:
    name: '{{ item }}'
    state: restarted
  loop:
        - docker
