# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: app-pv
# spec:
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/mnt/data"  
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: hivebox-storage
# spec:
#   accessModes:
#     - ReadWriteOnce  
#   resources:
#     requests:
#       storage: 1Gi  
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      automountServiceAccountToken: false
      containers:
      - name: python
        image: ghcr.io/rezo7895/hivebox:1736335526
        ports:
        - containerPort: 5000
        - containerPort: 9090
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "120m"
            memory: "150Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: python
spec:
  selector:
    app: python
  ports:
    - protocol: TCP
      name: port1
      port: 80
      targetPort: 5000
    # - protocol: TCP
    #   name: port2
    #   port: 9090
    #   targetPort: 9090
    #   nodePort: 30001
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: " "
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /version
        pathType: Prefix
        backend:
          service:
            name: app-service
            port:
              number: 80
      - path: /temperature
        pathType: Prefix
        backend:
          service:
            name: app-service
            port:
              number: 80
      - path: /metrics
        pathType: Prefix
        backend:
          service:
            name: app-service
            port:
              number: 80

